// models.js generated by update_model_js.py. EDIT WITH CAUTION!
var model_index = [
		{title: "Eenvoudig SIR virus model (Arjan vd Meij)", url: "modellen/virus01.xml"},
		{title: "SIR virus model - met overledenen (Arjan vd Meij)", url: "modellen/virus02.xml"},
		{title: "SIR model (Tom Kooij)", url: "modellen/sir.xml"},
];

